id: IAE1BB4EB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:18:12+00:00'
last_modified: '2022-06-07T21:33:49.188955+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ896
  title: སྙིང་ཐིག་གི་སྔོན་འགྲོའི་ཁྲིད་རིམ་ཐར་ལམ་སྣང་སྒྲོན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E8A0:
      image_group_id: I1CZ1050
      title: ''
      total_pages: 368
      order: 1
      base_file: E8A0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
